WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "tests_12_4.py", line 27, in test_run
    tr = Runner(name=25)
  File "С:\Python_project\module_12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "tests_12_4.py", line 16, in test_walk
    tw = Runner('Pit', speed=-5)
  File "С:\Python_project\module_12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
